export const SITE = {
  website: "https://supermilk-niuru-github-io.vercel.app/", 
  author: "Supermilk-Niuru",
  profile: "https://satnaing.dev/",
  desc: "Niuru's Blog",
  title: "Niuru's Blog",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000, 
  showArchives: true,
  showBackButton: true, 
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "https://github.com/Supermilk-Niuru/Supermilk-Niuru.github.io/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr", 
  lang: "en", 
  timezone: "Asia/Shanghai", 
} as const;
